version: '3.8'
services:

  postgres:
        image: postgres
        restart: always
        environment:
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
          - '5433:5432'
        volumes:
          - docker-subscribify-postgres:/var/lib/postgresql/data
    

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      target: development
    volumes:
      - ./api:/app/api
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    command: npm run start:dev
    ports:
      - 5000:5000
    depends_on:
      - postgres
 
  
  web:
    build:
      dockerfile: Dockerfile
      context: ./web
    volumes:
      - ./web:/app/web
    command: npm run dev
    ports:
      - 3000:3000

volumes:
  docker-subscribify-postgres:

  
